### PR TITLE
Adding support for the Date Datatype

### PR DESCRIPTION
**Pull request by s7clarke10**
## Problem

Some data coming from various taps may contain date data e.g. 2021-09-28 and have no time component i.e. it is a datatype of date. Adding a timestamp doesn't make sense especially when you need to factor in different timezones.

I live in New Zealand, and we have daylight savings and find that the conversion of dates with a datetime datatype can cause issues. If the tap / database natively supports a date datatype e.g. MSSQL, I would like to support providing the data in its native format.

## Proposed changes

This is a simple change that if the tap has exposed in the schema data with a date datatype that it would be treated as a Snowflake date rather than a string.

## Types of changes

What types of changes does your code introduce to PipelineWise?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

- [x] Description above provides context of the change
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] Unit tests for changes (not needed for documentation changes)
- [x] CI checks pass with my changes
- [ ] Bumping version in `setup.py` is an individual PR and not mixed with feature or bugfix PRs
- [ ] Commit message/PR title starts with `[AP-NNNN]` (if applicable. AP-NNNN = JIRA ID)
- [ ] Branch name starts with `AP-NNN` (if applicable. AP-NNN = JIRA ID)
- [ ] Commits follow "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)"
- [ ] Relevant documentation is updated including usage instructions

### CODE REVIEW

**Comment by Samira-El** [comment]
Hey @s7clarke10, thanks for the PR, the change makes sense! 

Do you mind adding few streams which have dates to our integration test fixtures [here](https://github.com/transferwise/pipelinewise-target-snowflake/tree/master/tests/integration/resources) ?

**Comment by s7clarke10** [comment]
> Hey @s7clarke10, thanks for the PR, the change makes sense!
> 
> Do you mind adding few streams which have dates to our integration test fixtures [here](https://github.com/transferwise/pipelinewise-target-snowflake/tree/master/tests/integration/resources) ?

Thanks for your support for this change. I have updated the integration tests to test the date datatype now and have successfully run all the tests. I felt it was best to add the test into the main data tests to ensure it had reasonable coverage over all the integration test.

**Comment by Samira-El** [comment]
Looks like Pylint isn't happy, do you mind taking a look?

**Comment by s7clarke10** [comment]
Sure will do. Hopefully it is just something small.

**Review by s7clarke10 — COMMENTED** [review]
There was white space at the end of line 86. This has been resolved. The CLI pylint is showing a 10/10 pass.

**Review by amofakhar — APPROVED** [review]
LGTM

**Pull request merged**
